name: Android Build

on: [push]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux dependencies
      run: sudo apt install ninja-build

    - name: Install Android dependencies
      run: ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-34"
      
    - name: Install Qt for Android
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.1.*'
        version: '6.6.0'
        host: 'linux'
        target: 'android'
        arch: 'android_arm64_v8a'
        modules: 'qtpositioning qtlocation qtconnectivity qtimageformats qtnetworkauth qtsensors qt5compat'
        extra: --autodesktop
    
    - name: Set up QT_HOST_PATH
      run: echo "QT_HOST_PATH=${{  github.workspace  }}/Qt/6.6.0/gcc_64" >> $GITHUB_ENV

    - name: Set up QT_HOST_PATH_CMAKE_DIR
      run: echo "QT_HOST_PATH_CMAKE_DIR=${{  github.workspace  }}/Qt/6.6.0/gcc_64/lib/cmake" >> $GITHUB_ENV

    - name: Set up Qt6CoreTools_DIR
      run: echo "Qt6CoreTools_DIR=${{  github.workspace  }}/Qt/6.6.0/gcc_64/lib/cmake/Qt6CoreTools" >> $GITHUB_ENV
      
    - name: Set up QT_FORCE_FIND_TOOLS
      run: echo "QT_FORCE_FIND_TOOLS=ON" >> $GITHUB_ENV
      
    - name: Configure CMake
      run: |
        cmake -S ./frontend-refactor -B build -G "Ninja Multi-Config" \
        env:
          QT_HOST_PATH: ${{ github.workspace }}/Qt/6.6.0/gcc_64
          QT_HOST_PATH_CMAKE_DIR: ${{ github.workspace }}/Qt/6.6.0/gcc_64/lib/cmake/Qt6
          Qt6CoreTools_DIR: ${{ github.workspace }}/Qt/6.6.0/gcc_64/lib/cmake/Qt6CoreTools

    - name: Build
      run: cmake --build build --config Debug
