name: Ubuntu Build

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: '⚙️ Install dependencies'
      run: |
        sudo apt-get update
        sudo apt install qtbase5-dev
        sudo apt install ninja-build

    - name: Install Qt for Linux
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.1.*'
        version: '6.7.0'
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'
        modules: 'qtpositioning qtlocation qtconnectivity qtimageformats qtsensors qt5compat'
        cache: "true"

    - name: Build
      run: cmake -S ./frontend -B build -G "Ninja Multi-Config" && cmake --build build --config Debug
    
    - name: install libfuse
      run: sudo apt-get install -y libfuse2
    
    - name: AppImage
      run: |
          wget -O deploy.AppImage https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod +x deploy.AppImage
          export PATH=${{ github.workspace }}/Qt/6.7.0/gcc_64/lib/
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ github.workspace }}/Qt/6.7.0/gcc_64/lib/
          ./deploy.AppImage build/Debug/frontend -appimage  -platform offscreen -no-translations -qmldir=../frontend/qml -qmlimport={{ github.workspace }}/Qt/6.7.0/gcc_64/lib/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/Debug/
