name: Ubuntu Build

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux dependencies
      run: sudo apt install ninja-build
    
    - name: Install Qt for Linux
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.1.*'
        version: '6.7.0'
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'
        modules: 'qtpositioning qtlocation qtconnectivity qtimageformats qtnetworkauth qtsensors qt5compat'
        cache: "true"

    - name: Build
      run: cmake -S ./frontend -B build -G "Ninja Multi-Config" && cmake --build build --config Debug

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/Debug/
