name: 🐧 Linux Build

on: [push]

# defaults:
 # run:
    # working-directory: frontend    #only our frontend build
env:
  BUILD_DIR: 'build'
  EXECUTABLE: "RouteGuide"
  APPLICATION: "RouteGuide"
  UNIXNAME: "RouteGuide"
  QMAKE_PROJECT: "QOwnNotes.pro"
  PUBLISHER: "Malte Kanders"
  REPO_DIR: "/home/runner/work/RouteGuide/"
  QT_MODULES: 'qtpositioning qtlocation qtconnectivity qtimageformats qtsensors qt5compat'
  CORES: 16

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: '🧰 Checkout repository'
      uses: actions/checkout@v4

    - name: '⚙️ Install dependencies'
      run: |
        sudo apt-get update
        sudo apt install qtbase5-dev
        sudo apt install desktop-file-utils libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-composite0 libxcb-cursor0 libxcb-damage0 libxcb-dpms0 libxcb-dri2-0 libxcb-dri3-0 libxcb-ewmh2 libxcb-glx0 libxcb-present0 libxcb-randr0 libxcb-record0 libxcb-render0 libxcb-res0 libxcb-screensaver0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-util1 libxkbcommon-x11-0
        sudo apt install ninja-build
        sudo apt-get install -y libfuse2

    - name: '⚙️ Install Linux QT'
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.1.*'
        version: '6.7.0'
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'
        modules: ${{ env.QT_MODULES }}
        cache: "true"

    - name: '👷 Compile'
      run: | 
       cmake -S ./frontend -B build -G "Ninja Multi-Config" && cmake --build build --config Release -DCMAKE_INSTALL_PREFIX=/usr
       
       sudo cp ./frontend/RouteGuide.png build/Release/
       sudo cp ./frontend/RouteGuide.desktop build/Release/

       cd build/Release/

       export PATH=${{ github.workspace }}/Qt/6.7.0/gcc_64/libexec:$PATH
       export PATH=${{ github.workspace }}/Qt/6.7.0/gcc_64/bin:$PATH
       
       wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
       wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
       chmod +x linuxdeploy-x86_64.AppImage
       chmod +x linuxdeploy-plugin-qt-x86_64.AppImage

       ./linuxdeploy-x86_64.AppImage ./RouteGuide -appimage -d RouteGuide.desktop
          
     #sudo mkdir appdir
     #cmake ./frontend -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
     #make -j$(nproc)
     #make DESTDIR=appdir -j$(nproc) install ; find appdir/

     
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/Release/

    # - name: '💂‍♂️ Install Linuxdeploy'
    
    #- name: '🌀 App Image'
        

